### ISSUE TITLE
vdrift doesn't detect GL version correctly due to not setting core context

### ISSUE THREAD

**Issue by niner** [VDrift/vdrift#123]
Mesa's r600 driver now supports OpenGL 3.3 as indicated by glxinfo:

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD REDWOOD
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.2.0-devel
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

But vdrift still only detects GL version 3.0, since it does not set GL context to core:

INFO: GL Renderer: Gallium 0.4 on AMD REDWOOD
INFO: GL Vendor: X.Org
INFO: GL Version: 3.0 Mesa 10.2.0-devel
INFO: Initialized GLEW 1.9.0
ERROR: Graphics card or driver does not support required GL_VERSION_3_3
ERROR: Initialization of GL3 failed; that's OK, falling back to GL 1 or 2
INFO: Video card information:
      Vendor: X.Org
      Renderer: Gallium 0.4 on AMD REDWOOD
      Version: 3.0 Mesa 10.2.0-devel
      Maximum texture size: 16384
      Maximum varying floats: 128
      Using GLEW 1.9.0

When forcing GL version to 3.3 using MESA_GL_VERSION_OVERRIDE=3.3 vdrift fails to initialize OpenGL with the following error message:

ERROR: OpenGL error "invalid enumerant" during: bool GLWrapper::initialize():src/gl3v/glwrapper.cpp:67

The game hangs on startup with a black screen and spewing OpenGL error "invalid enumerant" and OpenGL error "invalid operation" messages on the console.

**Comment by logzero** [comment]
Closing as fixed. Please open a new issue, if you still have any opengl related problems.
