### ISSUE TITLE
Bullet 2.82

### ISSUE THREAD

**Issue by logzero** [VDrift/vdrift#125]
Looks like Bullet 2.82 has got some major internal changes, which are thoroughly breaking our simulation (wheel contact, car flying off into the void and all that nice stuff).

Need to investigate.

**Comment by Timo6** [comment]
I can't replicate the problems with Bullet 2.83.5 (https://github.com/bulletphysics/bullet3/releases/tag/2.83.5)

**Comment by logzero** [comment]
Yeah, I've been running 2.83 locally for some time, just haven't done any test driving.

**Comment by logzero** [comment]
Updated min requirements to bullet 2.83

**Comment by Mailaender** [comment]
Is there a patch to fix compilation with bullet 2.83? The last released version from 2014 will only allow for bullet 2.82
