### ISSUE TITLE
Vdrift doesn't install in Ubuntu 15.04

### ISSUE THREAD

**Issue by caraffa** [VDrift/vdrift#135]
Hallo.
I've tried to install VDrift in ubuntu 15.04 using 

>sudo apt-get install vdrift

but this is what i get:

I seguenti pacchetti hanno dipendenze non soddisfatte:
> vdrift : Dipende: libbullet0 (>= 2.81) ma non è installabile
>         Dipende: libglew1.8 (>= 1.8.0) ma non è installabile
>         Dipende: libsdl-gfx1.2-4 (>= 2.0.22) ma non è installabile
> E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

Apparently, the package libbulet0 doesn't exist anymore. I think it is packaged with a different name.
Is there a way to circumvent this?

Thanks

**Comment by logzero** [comment]
Hi caraffa

We don't provide packages for distros ourselves. The best thing would probably be to contact the package maintainer.

Btw recent VDrift versions don't depend on glew and sdl-gfx anymore.

**Comment by caraffa** [comment]
Thank you Logzero. Apparently the maintainer has read our message because now "sudo apt-get install vdrift" worked flawlessly
