### ISSUE TITLE
Where is the Calibration menu ?

### ISSUE THREAD

**Issue by P1kachu** [VDrift/vdrift#153]
I'm trying to add a controller, and thus went to `Options -> Controls` (as explained [here](https://github.com/VDrift/vdrift/blob/master/docs/Configuring_the_controls.md)), but there is no "Joystick" nor "Calibration" menu. 

How can I add my evdev device without this ?

**Comment by logzero** [comment]
That looks like outdated info. You should be able to use your device as long as it is detected by sdl2.
