### ISSUE TITLE
Some errors on cars

### ISSUE THREAD

**Issue by leillo1975** [VDrift/vdrift#176]
I found a lot of errors on cars. Take a look to this screenshots:
![Captura de pantalla de 2020-08-27 22-10-09](https://user-images.githubusercontent.com/551821/91490583-f62a2000-e8b2-11ea-89d1-391706e7fe83.png)
![Captura de pantalla de 2020-08-27 22-10-51](https://user-images.githubusercontent.com/551821/91490597-fe825b00-e8b2-11ea-97ba-8a0fa49168c8.png)
![Captura de pantalla de 2020-08-27 22-11-09](https://user-images.githubusercontent.com/551821/91490604-00e4b500-e8b3-11ea-9280-2447149849eb.png)
![Captura de pantalla de 2020-08-27 22-11-19](https://user-images.githubusercontent.com/551821/91490608-03470f00-e8b3-11ea-9e6b-a88b672fe0f8.png)
![Captura de pantalla de 2020-08-27 22-10-29](https://user-images.githubusercontent.com/551821/91490587-f9bda700-e8b2-11ea-8d23-47282815be8d.png)

These are only some examples, but affects more cars. I use Ubuntu 20.04 and Nvidia GTX1060 with 450.66 drivers, but I have seen these errors for quite some time.

**Comment by logzero** [comment]
Check output or log.txt. It should tell you what went wrong.

**Comment by leillo1975** [comment]
Is very, very strange. Sometimes the car is loaded with problems, and then your reload it and it goes ok. I left you a video to see the problem:
https://youtu.be/mrYnZhTuDMw

The log is here:
[log.txt](https://github.com/VDrift/vdrift/files/5144180/log.txt)

**Comment by logzero** [comment]
> ERROR: Failed to load "oem_wheel_rear.joe" from:
> ...

It essentially fails to open the file for some reason. Not much you can do from VDrift side I'm afraid. Maybe some file system issue?

Btw VDrift caches loaded objects. So if it loading was successful once it will be reused.

**Comment by leillo1975** [comment]
I investigate some time and :
```
ERROR: Failed to load "oem_wheel_rear.joe" from:
       /home/leo/.vdrift/cars/F1-02
       /media/COMP/VDRIFT/share/games/vdrift/data/cars/F1-02
       /media/COMP/VDRIFT/share/games/vdrift/data/carparts
       /media/COMP/VDRIFT/share/games/vdrift/data/trackparts
```
There aren't a file called "oem_wheel_rear.joe" in none of these directories, but not in the repositories either:

https://svn.code.sf.net/p/vdrift/code/vdrift-data/cars/F1-02/
https://svn.code.sf.net/p/vdrift/code/vdrift-data/carparts/
https://svn.code.sf.net/p/vdrift/code/vdrift-data/trackparts/

Really, it's very strange

**Comment by logzero** [comment]
You are correct it should be oem_wheel.joe. I overlooked the rear/front parts.

Check your F1-02.car file. It seems that it is outdated. 

If there is a car file in /home/leo/.vdrift/cars/F1-02 it will be preferred over /media/COMP/VDRIFT/share/games/vdrift/data/cars/F1-02.

**Comment by logzero** [comment]
I've changed the loading code a bit just to be sure the compiler doesn't do anything funny.

**Comment by leillo1975** [comment]
> 
> Check your F1-02.car file. It seems that it is outdated.
> 

I redownloaded code and data some days ago, before this problems

**Comment by logzero** [comment]
If you have /home/leo/.vdrift/cars/ directory delete it.

The F1-02.car file should not contain oem_wheel_rear.joe if it is up to date.

**Comment by leillo1975** [comment]
I don't have any cars directory on .vdrift folder. I loaded the game again and didn't have problems, but I closed and reopen and have this again:
![Captura de pantalla de 2020-08-30 18-12-38](https://user-images.githubusercontent.com/551821/91664003-8bfcbf80-eaec-11ea-8a4d-7e6e121abdd9.png)

**Comment by leillo1975** [comment]
I'm thinking on something. The previous car I loaded was AX2 that it has the missing files. F1-02 don't need this files (I think). Could it be a problem of . car files info getting mixed up?

**Comment by logzero** [comment]
The car specs are in your screenshots are completely wrong too. No idea how that is possible.

What you could test is replacing in game.cpp line 1729

content.load(carconf, cardir, carname + ".car");

with

std::string abspath = pathmanager.GetDataPath() + "/" + pathmanager.GetCarsDir() + "/" + info.name + ".car";
std::ifstream carfile(abspath.c_str());
carconf.reset(new PTree());
read_ini(carfile, *carconf);

This will load the file without any caching.

**Comment by leillo1975** [comment]
I have the same problem with this changes. I ran the game and then I changed cars, but it failed again. You can see the log here:
[log.txt](https://github.com/VDrift/vdrift/files/5147486/log.txt)

**Comment by logzero** [comment]
Let's try dumping the carconfig after parsing.

In game.cpp line 1745 add:

write_ini(*carconf, info_output);

log.txt should then contain the corrupted config I assume.

**Comment by leillo1975** [comment]
I have added this line and made the following:
https://youtu.be/cpii5mZtr6o

This is the log:
[log.txt](https://github.com/VDrift/vdrift/files/5151600/log.txt)

I have noticed that the problem don't appear if you change the car on garage, but if you load a race and then go to main menu, and then you go to garage again, the problem is showed, as you can see on the video.

**Comment by logzero** [comment]
I think I got it. You have replay recording enabled, which stores config in car_info, but doesn't clear it when you select a different car.

Will look into a fix tomorrow.

Thank you.

**Comment by logzero** [comment]
Commit 9ef27c6486276f4ddd60b70661655f227f7f4857 should fix it.

**Comment by leillo1975** [comment]
Seems to work great now. Thanks a lot for the support!

**Comment by leillo1975** [comment]
Hi, I found an error on F40:
![Captura de pantalla de 2021-03-28 22-49-58](https://user-images.githubusercontent.com/551821/112767811-0f49a980-9019-11eb-9712-55043ebee15b.png)
![Captura de pantalla de 2021-03-28 22-50-14](https://user-images.githubusercontent.com/551821/112767816-12449a00-9019-11eb-8510-5e242aa87e82.png)

**Comment by leillo1975** [comment]
The error on F40 was not corrected and the issue is closed
