### ISSUE TITLE
I only see the wheels in the 350Z car 

### ISSUE THREAD

**Issue by leillo1975** [VDrift/vdrift#178]
Hello

I compiled and installed VDRIFT and have a problem with 350Z car. I only can see the wheels like you can see in the following screenshot:
https://i.imgur.com/GUt6Fih.png

Here is the terminal output:
_INFO: Multi-processor system detected.  Run with -multithreaded argument to enable multithreading (EXPERIMENTAL).
INFO: Starting VDrift: 2020-11-25-full, Revision: Unversioned directory, O/S: Unix
INFO: Home directory: /home/leo
INFO: Settings file: /home/leo/.vdrift/VDrift.config
INFO: Data directory: /media/VDRIFT/share/games/vdrift/data
      DATA_DIR: /media/VDRIFT/share/games/vdrift/data
INFO: Temporary directory: /home/leo/.vdrift/tmp
INFO: Log file: /home/leo/.vdrift/log.txt
INFO: Request OpenGL 3.3 Core Profile context.
INFO: Disabling antialiasing
INFO: Disabling vertical synchronization.
INFO: Video card information:
      GL Vendor: NVIDIA Corporation
      GL Renderer: GeForce GTX 950/PCIe/SSE2
      GL Version: 3.3.0 NVIDIA 450.80.02
      Texture units: 32
      Maximum texture size: 16384
INFO: Loading /media/VDRIFT/share/games/vdrift/data/shaders/gl3/deferred.conf...
INFO: Loaded /media/VDRIFT/share/games/vdrift/data/shaders/gl3/deferred.conf
INFO: GL3 initialization successful
INFO: 0 joysticks found.
INFO: Loading car controls from: /home/leo/.vdrift/controls.config
INFO: Obtained audio device:
      Frequency: 44100
      Format: 32784
      Bits per sample: 16
      Channels: 2
      Silence: 0
      Samples: 512
      Size: 2048
INFO: Sound initialization successful
INFO: Loaded fonts successfully
INFO: Loaded GUI successfully
INFO: No force feedback devices found.
INFO: Loading track from path: /media/VDRIFT/share/games/vdrift/data/tracks/.room
INFO: Loaded surfaces file, 2 surfaces.
INFO: No roads loaded. Skip loading lap timing sectors. Lap timing will not be possible.
ERROR: .body.mesh not found.
INFO: Car loading was successful: 350Z_

**Comment by leillo1975** [comment]
Seems to be repaired in the last commiits:

https://sourceforge.net/p/vdrift/code/1436/log/?path=/vdrift-data

**Comment by logzero** [comment]
Yeah, some testing modifications ended up in main. I've reverted them.

**Comment by leillo1975** [comment]
Thanks a lot!
