### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by jhonny-oliveira** [VDrift/vdrift#180]
Hi!

I have recently packaged VDrift and published it here: https://launchpad.net/~xtradeb/+archive/ubuntu/play
I came across a couple of issues, such as the Python 2 dependency in the current official release (20141020), so I ended up creating a new "virtual" release with the latest code/data. Sorry for that!

I also came across a few other findings, please let me know the best way forward.

- The game has its own metadata, Desktop file and icons:
  - usr/share/applications/vdrift.desktop
  - usr/share/metainfo/vdrift.appdata.xml
  - usr/share/games/vdrift/data/textures/icons/
  but
  - the desktop file cannot load the icon, due to its non standard location;
  - the metadata is in a very old format, so I create a quilt patch for the package;
  - the data (rev 1436) has an empty file "data/tracks/brands/.zip"
- At the moment, the game binaries and data are not packaging/watch file friendly. Having a new release and download ready "zip"/txz files would be welcome.

Cheers!
Jhonny

**Comment by Apteryks** [comment]
@logzero I guess this empty file can be simply deleted: https://sourceforge.net/p/vdrift/code/HEAD/tree/vdrift-data/tracks/brands/.zip

Then this issue can be closed, I believe, unless you think the last point should be tackled, but I don't see a big problem with the status quo.
