### ISSUE TITLE
VDrift data not found even after compiling with "scons"

### ISSUE THREAD

**Issue by nmcy2005** [VDrift/vdrift#185]
After downloading "vdrift-master" and compiling it, I want to install it with "scons install". But I get an error saying:

`scons: Reading SConscript files ...
Checking for C++ header file GL/gl.h... (cached) yes
Checking for C++ header file SDL2/SDL.h... (cached) yes
Checking for C++ header file SDL2/SDL_image.h... (cached) yes
Checking for C++ header file vorbis/vorbisfile.h... (cached) yes
Checking for C++ header file curl/curl.h... (cached) yes
Checking for C++ header file bullet/btBulletCollisionCommon.h... (cached) yes
Checking for C++ header file bullet/btBulletDynamicsCommon.h... (cached) yes
TypeError: exceptions must be old-style classes or derived from BaseException, not str:
  File "/home/nomercy1002/vdrift-master/SConstruct", line 514:
    raise 'VDrift data not found. Please make sure data is placed in vdrift directory. See README.md and http://wiki.vdrift.net.'
`

Could you help me?

**Comment by nmcy2005** [comment]
And, after trying to run it without installing by typing ./vdrift in the build folder, I get following errors:

`INFO: Multi-processor system detected.  Run with -multithreaded argument to enable multithreading (EXPERIMENTAL).
INFO: Starting VDrift: development-full, Revision: Unversioned directory, O/S: Unix
INFO: Home directory: /home/nomercy
INFO: Settings file: /home/nomercy/.vdrift/VDrift.config (does not exist, will be created)
INFO: Data directory: /usr/local/share/games/vdrift/data
      DATA_DIR: /usr/local/share/games/vdrift/data
INFO: Temporary directory: /home/nomercy/.vdrift/tmp
INFO: Log file: /home/nomercy/.vdrift/log.txt
ERROR: Failed to load /home/nomercy/.vdrift/VDrift.config
INFO: The last VDrift startup was unsuccessful.
      Settings have been set to failsafe defaults.
      Your original VDrift.config file was backed up to VDrift.config.backup
INFO: Request OpenGL 3.3 Core Profile context.
INFO: Disabling antialiasing
INFO: Disabling vertical synchronization.
INFO: Video card information:
      GL Vendor: X.Org
      GL Renderer: AMD RV610 (DRM 2.50.0 / 5.8.0-48-generic, LLVM 11.0.0)
      GL Version: 3.3 (Core Profile) Mesa 20.2.6
      Texture units: 16
      Maximum texture size: 8192
INFO: Maximum anisotropy: 16
INFO: Maximum color attachments: 8
INFO: Maximum draw buffers (1 required): 8
ERROR: Error loading texture file: /usr/local/share/games/vdrift/data/textures/weather/cubereflection-nosun.png
ERROR: Couldn't open /usr/local/share/games/vdrift/data/textures/weather/cubereflection-nosun.png
ERROR: Error loading texture file: /usr/local/share/games/vdrift/data/textures/weather/cubelighting.png
ERROR: Couldn't open /usr/local/share/games/vdrift/data/textures/weather/cubelighting.png
ERROR: Unable to open graphics config file: /usr/local/share/games/vdrift/data/shaders/gl2/basic.conf
ERROR: EnableShaders: Error loading render configuration file: /usr/local/share/games/vdrift/data/shaders/gl2/basic.conf
INFO: Renderer: /usr/local/share/games/vdrift/data/shaders/gl2/basic.conf
INFO: 1 joystick found:
INFO:     0 Logitech Logitech Racing Wheel
INFO: Loading car controls from: /home/nomercy/.vdrift/controls.config
INFO: Update status file /home/nomercy/.vdrift/updates.config will be created
ERROR: Unable to load update manager base file: /usr/local/share/games/vdrift/data/settings/updates.config; updates will start from scratch
ERROR: Car update manager failed to initialize; this error is not fatal
INFO: Update status file /home/nomercy/.vdrift/updates.config will be created
ERROR: Unable to load update manager base file: /usr/local/share/games/vdrift/data/settings/updates.config; updates will start from scratch
ERROR: Track update manager failed to initialize; this error is not fatal
INFO: Obtained audio device:
      Frequency: 44100
      Format: 32784
      Bits per sample: 16
      Channels: 2
      Silence: 0
      Samples: 512
      Size: 2048
INFO: Sound initialization successful
ERROR: Failed to load "freesans.png" from:
       /home/nomercy/.vdrift/skins/simple/fonts
       /usr/local/share/games/vdrift/data/skins/simple/fonts
       /usr/local/share/games/vdrift/data/carparts
       /usr/local/share/games/vdrift/data/trackparts
ERROR: Can't find font information file: /usr/local/share/games/vdrift/data/skins/simple/fonts/freesans.txt
ERROR: Error loading fonts
INFO: Exiting
`

**Comment by logzero** [comment]
Do you have vdrift data?

`svn co https://vdrift.svn.sourceforge.net/svnroot/vdrift/vdrift-data data`

See: https://github.com/VDrift/vdrift/blob/master/docs/Getting_the_development_version.md

**Comment by nmcy2005** [comment]
When running the command, i get a path mit found Error. Svn: E160013

**Comment by logzero** [comment]
Seems the URL is outdated.

Try: `svn co https://svn.code.sf.net/p/vdrift/code/vdrift-data data`
