### ISSUE TITLE
Cannot run the compiled binary on Windows

### ISSUE THREAD

**Issue by vtereshkov** [VDrift/vdrift#187]
I have compiled `vdrift.exe` under MSYS2, according to the instructions here: https://github.com/VDrift/vdrift/blob/master/docs/Compiling.md

However, I cannot run it. When running from the MSYS2 console, I get 
```
vtere@Vasiliy-Acer MSYS ~/vdrift/build
$ ./vdrift.exe
INFO: Starting VDrift: development-full, Revision: , O/S: Windows
INFO: Home directory: C:\Users\vtere
INFO: Settings file: C:\Users\vtere\AppData\Roaming\VDrift/VDrift.config
INFO: Data directory: data
INFO: Temporary directory: C:\Users\vtere\AppData\Roaming\VDrift/tmp
INFO: Log file: C:\Users\vtere\AppData\Roaming\VDrift/log.txt
INFO: The last VDrift startup was unsuccessful.
      Settings have been set to failsafe defaults.
      Your original VDrift.config file was backed up to VDrift.config.backup
INFO: Request OpenGL 3.3 Core Profile context.
INFO: Disabling antialiasing
INFO: Disabling vertical synchronization.
INFO: Video card information:
      GL Vendor: Intel
      GL Renderer: Intel(R) UHD Graphics
      GL Version: 3.3.0 - Build 28.20.100.8322
      Texture units: 32
      Maximum texture size: 16384
INFO: Maximum anisotropy: 16
INFO: Maximum color attachments: 8
INFO: Maximum draw buffers (1 required): 8
INFO: Renderer: data/shaders/gl2/basic.conf
INFO: 0 joysticks found.
INFO: Loading car controls from: C:\Users\vtere\AppData\Roaming\VDrift/controls.config
INFO: Update status file C:\Users\vtere\AppData\Roaming\VDrift/updates.config will be created
INFO: Update status file C:\Users\vtere\AppData\Roaming\VDrift/updates.config will be created
INFO: Obtained audio device:
      Frequency: 44100
      Format: 33056
      Bits per sample: 32
      Channels: 2
      Silence: 0
      Samples: 441
      Size: 3528
INFO: Sound initialization successful
INFO: Loaded fonts successfully
ERROR: Widget ConnectActions failed: widget-18b widget-18b
ERROR: Widget ConnectActions failed: widget-18b widget-18b
ERROR: Widget ConnectActions failed: widget-01b widget-01b
ERROR: ParseActions: Unknown action ailevel-bar.opacity:0 ailevel-bar.opacity
ERROR: ParseActions: Unknown action ailevel-bar.opacity:1 ailevel-bar.opacity
...
ERROR: Widget ConnectActions failed: gui.options.load LoadControls gui.page:CarControls gui.options.load
INFO: Loaded GUI successfully
Assertion failed: it != options.end(), file src/gui/gui.cpp, line 554
```

If I copy my `vdrift.exe` and `libBullet*.dll` into a new folder (or just replace the files in the existing VDrift installation folder) and try to run it as I usually do on Windows, I see the error message like `_ZdlPvy entry point not found in libBulletCollision.dll`.

**Comment by vtereshkov** [comment]
Furthermore, when I generate a Code::Blocks project, compile and run it, I get the same assertion failure: `it != options.end(), file src/gui/gui.cpp, line 554`. On the other hand, the old source corresponding to the latest (2014) release, compiles and runs well.

**Comment by logzero** [comment]
Make sure you use latest data with latest code. Mixing old and new wont work.

VDrift depends on a bunch of dlls, about 30 or so.

If you are using MInGW or Msys2 just start vdrift from the shell.

**Comment by vtereshkov** [comment]
@logzero Not sure about the latest data. Where to get them for x64 + Windows + MinGW?

**Comment by logzero** [comment]
https://sourceforge.net/p/vdrift/code/HEAD/tree/vdrift-data/
svn co https://svn.code.sf.net/p/vdrift/code/vdrift-data data

**Comment by vtereshkov** [comment]
@logzero Thank you, it works. However, can I remove some of the tracks from the `data` folder to make it not so huge? Will the simulator still run correctly on any of the remaining tracks?

**Comment by logzero** [comment]
Yes you can remove tracks as you please, except for the menu ".room". The game checks the available track in the folder at start.
