### ISSUE TITLE
Proposal: Embedded scripting in Umka

### ISSUE THREAD

**Issue by vtereshkov** [VDrift/vdrift#188]
I have designed a new embeddable scripting language, [Umka](https://github.com/vtereshkov/umka-lang). In contrast to Lua, it is statically typed, so that type mismatch errors are detected at compile time rather than run time. It also supports classical data types such as C-like arrays and structures.

I would like to add Umka scripting to VDrift. This would be useful for many purposes like reprogramming AI or using VDrift in automatic control system design courses where it could serve as a testbench for various steering controller prototypes.

Of course I can fork VDrift and do whatever I want. But if you are sure that a scripting language is absolutely unnecessary and contradicts the overall vision of the project, I’d better not waste time for these experiments.

**Comment by logzero** [comment]
I don't have much time to work on VDrift, so large scale code changes might be better done in a fork. StuntRally started as a VDrift fork and turned into cool racer on its own for example.

I wouldn't object scripting support if you can keep it optional (build option) and it doesn't modify too much code.

**Comment by vtereshkov** [comment]
Implemented as a VDrift fork: https://github.com/vtereshkov/vdrift
