### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by frearlv** [VDrift/vdrift#190]
Hi everyone, and happy new year.

I had success compiling on Linux, but I want to on Windows because of the wheel drivers.

I'm trying on Windows, but I'm getting this error.
"
$ scons
scons: Reading SConscript files ...
/bin/sh: line 1: pkg-config: command not found
OSError: 'pkg-config bullet --libs --cflags' exited 127:
  File "/e/SimRacing/Juegos/V-Drift/Compilable/vdrift-master/SConstruct", line 360:
    env.ParseConfig(env['pkg_config'] + ' bullet --libs --cflags')
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 1578:
    return function(self, self.backtick(command))
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 589:
    raise OSError("'%s' exited %d" % (command, status))
"
Is there something I can do?

Thanks very much in advance.

Regards.
Fernando.

**Comment by rapsys** [comment]
Install pkg-config binary that you are obviously missing...

You may close this issue as invalid afterward.

**Comment by frearlv** [comment]
Thanks very much.
